Harden the installer

diff --git a/install b/install
--- a/install
+++ b/install
@@ -3,10 +3,34 @@ set -Eeu -o pipefail
 
 # """
 # koopa piped install script.
-# Updated 2020-06-03.
+# Updated 2020-06-29.
 #
 # This downloads a copy of the latest stable release into a temporary directory.
 # """
+
+# shell/posix/functions/boolean-logical.sh
+_koopa_is_installed() {
+    command -v "$1" >/dev/null
+}
+
+# shell/posix/functions/print.sh
+_koopa_print() {
+    printf '%b\n' "${1:-}"
+    return 0
+}
+
+# Check dependencies before attempting to install.
+deps=(curl find git grep mktemp sudo tar)
+
+for dep in "${deps[@]}"
+do
+    if ! _koopa_is_installed "$dep"
+    then
+        >&2 printf "ERROR: '%s' is not installed.\n" "$dep"
+        >&2 printf "Required dependencies: %s\n" "${deps[*]}"
+        exit 1
+    fi
+done
 
 release="rolling"
 
@@ -40,9 +64,9 @@ repo="acidgenomics/koopa"
 
 if [[ "$release" == "rolling" ]]
 then
-    echo "Installing koopa."
-    echo "Using rolling release from master branch."
-    echo "This can be updated using 'koopa update'."
+    _koopa_print "Installing koopa."
+    _koopa_print "Using rolling release from master branch."
+    _koopa_print "This can be updated using 'koopa update'."
     git_url="https://github.com/${repo}.git"
     # Alternatively, here's how to get master branch tarball:
     # > tarball_url="https://github.com/${repo}/tarball/master"
@@ -51,21 +75,20 @@ else
     json_url="https://api.github.com/repos/${repo}/releases/${release}"
     json="$(curl -s "$json_url")"
     tarball_url="$( \
-        echo "$json" \
+        _koopa_print "$json" \
             | grep '"tarball_url":' \
             | cut -d '"' -f 4 \
     )"
     tag_name="$( \
-        echo "$json" \
+        _koopa_print "$json" \
             | grep '"tag_name":' \
             | cut -d '"' -f 4 \
     )"
-    echo "Installing koopa ${tag_name}."
-    echo "This is a stable release that cannot be updated."
+    _koopa_print "Installing koopa ${tag_name}."
+    _koopa_print "This is a stable release that cannot be updated."
 fi
 
 tmp_dir="$(mktemp -d)"
-# > echo "tmpdir: '${tmp_dir}'."
 
 (
     cd "$tmp_dir" || exit 1
